services:
  gai:
    build:
      context: .
      tags:
        - unknown
    command: ./gai hello world
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      KIMI_API_KEY: ${KIMI_API_KEY}
