name: "Release"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Cache asdf and Go modules cache
        uses: actions/cache@v4
        with:
          path: ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-asdf-

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Build the executable
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -ldflags="-s -w -X main.version=develop" -o gai-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Rename the executable
        if: ${{ matrix.goos }} == "windows"
        run: mv gai-${{ matrix.goos }}-${{ matrix.goarch }} gai-${{ matrix.goos }}-${{ matrix.goarch }}.exe

      - name: Package the executable
        if: ${{ matrix.goos != "windows" && matrix.goarch != "arm64" }}
        run: upx --best --lzma --force-macos gai*

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          preserve_order: true
          files: |
            gai-${{ matrix.goos }}-${{ matrix.goarch }}
            gai-${{ matrix.goos }}-${{ matrix.goarch }}.exe
